spring.config.import=optional:file:.env[.properties]
spring.application.name=spring-boot-jwt-template

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

